// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOkfvLD7vJa0SpnIdXsNI8c0mifUcrS4c',
    appId: '1:1048346189491:web:2d59809c287012ace71ac6',
    messagingSenderId: '1048346189491',
    projectId: 'fcmpushnotification-6a31c',
    authDomain: 'fcmpushnotification-6a31c.firebaseapp.com',
    databaseURL: 'https://fcmpushnotification-6a31c-default-rtdb.firebaseio.com',
    storageBucket: 'fcmpushnotification-6a31c.firebasestorage.app',
    measurementId: 'G-WYDM39B9N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw9PiFrjGkFqUkGI2XSS3O-uAhQxgfy-M',
    appId: '1:1048346189491:android:c7264759f683e541e71ac6',
    messagingSenderId: '1048346189491',
    projectId: 'fcmpushnotification-6a31c',
    databaseURL: 'https://fcmpushnotification-6a31c-default-rtdb.firebaseio.com',
    storageBucket: 'fcmpushnotification-6a31c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOkfvLD7vJa0SpnIdXsNI8c0mifUcrS4c',
    appId: '1:1048346189491:web:95d1c8b667a5fb18e71ac6',
    messagingSenderId: '1048346189491',
    projectId: 'fcmpushnotification-6a31c',
    authDomain: 'fcmpushnotification-6a31c.firebaseapp.com',
    databaseURL: 'https://fcmpushnotification-6a31c-default-rtdb.firebaseio.com',
    storageBucket: 'fcmpushnotification-6a31c.firebasestorage.app',
    measurementId: 'G-H4YKJ8KPQ0',
  );
}
